## 딥러닝 모델 돌릴 때 발생하는 pytorch 오류 정리

#### 1. RuntimeError: Expected object of scalar type Long but got scalar type Float when using CrossEntropyLoss
해결: target 변수를 다시 long 타입으로 바꿔준다<br>
[여기참조](https://discuss.pytorch.org/t/runtimeerror-expected-object-of-scalar-type-long-but-got-scalar-type-float-when-using-crossentropyloss/30542)
